version: "3.9"

services:
  store:
    build:
      context: .

    ports:
      - "8000:8000"

    volumes:
      - ./store:/store

    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=store_db
      - DB_NAME=store
      - DB_USER=store_user
      - DB_PASS=store

    depends_on:
      - store_db

  store_db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=store_user
      - POSTGRES_PASSWORD=store

volumes:
  dev-db-data:
