# Generated by Django 4.1.2 on 2022-10-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('complete', 'COMPLETE'), ('cancel', 'CANCEL')], max_length=255),
        ),
    ]
